package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.notifications
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'FailedBuildBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("FailedBuildBuild")) {
    check(name == "Failed build build") {
        "Unexpected name: '$name'"
    }
    name = "Failed build"

    features {
        remove {
            notifications {
                id = "BUILD_EXT_54"
                notifier = "email"
                brachFilter = "+:refs/heads/bbbb"
                buildStarted = true
                buildFailedToStart = true
                buildFailed = true
                firstFailureAfterSuccess = true
                newBuildProblemOccured = true
                buildFinishedSuccessfully = true
                firstBuildErrorOccurs = true
                buildProbablyHanging = true
                investigationUpdated = true
                muteUpdated = true
                param("email", "inna_yan@mail.ru")
            }
        }
        remove {
            notifications {
                id = "BUILD_EXT_55"
                notifier = "emai"
                brachFilter = "+:refs/heads/bbbb111"
                buildStarted = true
                buildFailedToStart = true
                buildFailed = false
                firstFailureAfterSuccess = true
                newBuildProblemOccured = true
                buildFinishedSuccessfully = true
                firstBuildErrorOccurs = true
                buildProbablyHanging = true
                investigationUpdated = true
                muteUpdated = true
                param("email", "inna_yan111@mail.ru")
            }
        }
        add {
            feature {
                id = "BUILD_EXT_53"
                type = "xml-report-plugin"
                param("xmlReportParsing.reportType", "ctest")
                param("xmlReportParsing.reportDirs", "ddd")
            }
        }
    }

    cleanup {
        add {
            keepRule {
                id = "KEEP_RULE_12"
                keepAtLeast = allBuilds()
                applyToBuilds {
                    withTags = anyOf("tag")
                }
                dataToKeep = historyAndStatistics {
                    preserveArtifacts = all()
                }
                applyPerEachBranch = true
                preserveArtifactsDependencies = true
            }
        }
    }
}
